[workspace]
members = ["fission-server"]

[workspace.dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
axum = { version = "0.6", features = ["headers"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ucan = "0.2.0"
ucan-key-support = "0.1.3"
url = "2.3"