[workspace]
members = ["fission-server"]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
axum = { version = "0.6", features = ["headers"] }
ed25519-zebra = "3.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
testresult = "0.3"
# rs-ucan = { git = "https://github.com/fission-codes/rs-ucan/", branch = "quinn-wip-rework" }
rs-ucan = { path = "../rs-ucan" }
url = "2.3"

# Speedup build on macOS
# See https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#splitting-debug-information
[profile.dev]
split-debuginfo = "unpacked"
