[workspace]
members = ["fission-server"]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
axum = { version = "0.6", features = ["headers"] }
ed25519 = "2.2.2"
ed25519-dalek = { version = "2.0.0", features = [
    "rand_core",
    "zeroize",
    "pem",
] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
test-log = { version = "0.2", default-features = false, features = ["trace"] }
testresult = "0.3"
rs-ucan = { git = "https://github.com/fission-codes/rs-ucan/", branch = "matheus23/allow-same-resource-scheme", revision = "5d272de3b49c233448d1e460812895c7d7f671b9" }
url = "2.3"
utoipa = { version = "3.1", features = ["uuid", "axum_extras"] }
validator = { version = "0.16.0", features = ["derive"] }

# Speedup build on macOS
# See https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#splitting-debug-information
[profile.dev]
split-debuginfo = "unpacked"
