[database]
url = "postgres://postgres:postgres@localhost:5432/fission-server"
connect_timeout = 3

[monitoring]
process_collector_interval = 10

[otel]
exporter_otlp_endpoint = "http://localhost:4317"

[server]
environment = "local"
did = "did:web:localhost"
metrics_port = 4000
port = 3000
timeout_ms = 30000

[mailgun]
api_key = 0
sender_address = "noreply@mail.fission.codes"
sender_name = "Fission"
domain = "mail.fission.codes"
subject = "Your Fission Verification Code"
from_address = "noreply@mail.fission.codes"
from_name = "Fission"
template = "test-email-verification"

[healthcheck]
enabled = true
interval_ms = 5000
max_retries = 3
