[database]
url = "postgres://postgres:postgres@localhost:5432/fission-server"
connect_timeout = 3

[healthcheck]
enabled = false
interval_ms = 5000
max_retries = 3

[ipfs]
peers = [
  "/ip4/127.0.0.1/tcp/4002/ws/p2p/12D3KooWLXH5BFzscChpdjtotAvv94hDR6bVxMKLHBHrSnugCRWs",
  "/ip4/127.0.0.1/udp/4001/quic-v1/webtransport/certhash/uEiC4_sAMUfcxEJtqIlVWRGlHrTSSYuyk5Ulqfl6CjRiOHw/certhash/uEiANUHX9dRBqphQzZINo5WzkStJ7qevCr_2ZAUzLEbqoFw/p2p/12D3KooWLXH5BFzscChpdjtotAvv94hDR6bVxMKLHBHrSnugCRWs"
]

[mailgun]
api_key = 0
sender_address = "noreply@mail.fission.codes"
sender_name = "Fission"
domain = "mail.fission.codes"
subject = "Your Fission Verification Code"
from_address = "noreply@mail.fission.codes"
from_name = "Fission"
template = "test-email-verification"

[monitoring]
process_collector_interval = 10

[otel]
exporter_otlp_endpoint = "http://localhost:4317"

[dns]
server_port = 1053
default_soa = "dns1.fission.systems hostmaster.fission.codes 0 10800 3600 604800 3600"
origin = "localhost" # used for serving the `_did.<origin>` DNS TXT entry
users_origin = "localhost" # used for serving the `_did.<username>.<users_origin>` DNS TXT entry

[server]
environment = "local"
keypair_path = "./server.ed25519.pem"
metrics_port = 4000
port = 3000
timeout_ms = 30000
